name: Build and Push

on: push

env:
  REGISTRY: ghcr.io
  IMAGE: ghcr.io/${{ github.repository }}

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    permissions:
      packages: write
    strategy:
      matrix:
        include:
          - arch: amd64
            runner: ubuntu-latest
            platform: linux/amd64
          - arch: arm64
            runner: ubuntu-arm
            platform: linux/arm64
            # runner: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Building for (${{ matrix.platform }})
        run: |
          docker buildx create --use
          docker buildx build \
          --platform ${{ matrix.platform }} \
          --tag ${{ env.IMAGE }}:${{ github.run_number }}-${{ matrix.arch }} \
          --push .

  manifest:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      packages: write
    steps:
      - name: Log in
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Manifest
        run: |
          docker manifest create ${{ env.IMAGE }}:latest ${{ env.IMAGE }}:${{ github.run_number }} \
          --amend ${{ env.IMAGE }}:${{ github.run_number }}-amd64 \
          --amend ${{ env.IMAGE }}:${{ github.run_number }}-arm64
          docker manifest ${{ env.IMAGE }}:latest ${{ env.IMAGE }}:${{ github.run_number }}
